#! /usr/bin/env zsh

name=`uname -n`

mp_ver='4.9'
env_str="CC=gcc-mp-$mp_ver CXX=g++-mp-$mp_ver FC=gfortran-mp-$mp_ver"

CC=gcc-mp-$mp_ver CXX=g++-mp-$mp_ver FC=gfortran-mp-$mp_ver ./build_all.generic
