#! /usr/bin/env zsh

name=`uname -n`

mp_ver='4.9'
env_str="CC=gcc-mp-$mp_ver CXX=g++-mp-$mp_ver FC=gfortran-mp-$mp_ver"

rm -Rf cpp/build && \
mkdir -p cpp/build && \
cd cpp/build && \
CC=gcc-mp-$mp_ver CXX=g++-mp-$mp_ver FC=gfortran-mp-$mp_ver cmake .. $* && \
cd ../.. && \

CC=gcc-mp-$mp_ver CXX=g++-mp-$mp_ver FC=gfortran-mp-$mp_ver ./make_all $*
